# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:   
    - task: Docker@2
      displayName: Build & Push an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'baneeishaque / gitpod-full-tint2-pcmanfm-zsh-as-gh-chrome-idea-pycharm-anaconda3-as-canary-handbrake-1366x625'
        command: 'buildAndPush'
        Dockerfile: '.gitpod.Dockerfile'
        tags: 'latest'